### ISSUE TITLE
[FEATURE] JetBrains plugin

### ISSUE THREAD

**Issue by az-z** [mineiros-io/terramate#889]
**Is your feature request related to a problem? Please describe.**
It would be great to have a plugin for [Idea](https://www.jetbrains.com/) IDEs.

**Comment by i4ki** [comment]
Hi @az-z 

I have good and bad news =/

I never used the JetBrains IDEs but I looked at how plugins work in the IntelliJ family of IDEs:

# [IntelliJ IDEA](https://www.jetbrains.com/idea/), [GoLand](https://www.jetbrains.com/go/), etc

The IntelliJ plugins are based on the [Gradle build system](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html) and they could be developed using Kotlin, Groovy, or Java. This means that developing a plugin for Terramate will involve coding the parser again in one of these languages and keeping it up to date with Terramate development. As an example, here's the HCL parser implemented in Java for the [IntelliJ terraform plugin](https://github.com/JetBrains/intellij-plugins/tree/master/terraform/src/java/org/intellij/terraform/hcl).

Then, the *bad news* is that implementing a native IntelliJ plugin is not going to happen anytime soon and the **Jetbrains IDEs** don't natively support [LSP](https://microsoft.github.io/language-server-protocol/) then maybe only if the community contributes one but still very unlikely because of the amount of work needed.

The good news is that in the [Jetbrains Marketplace](https://plugins.jetbrains.com/) there are some plugins that implement the *LSP client*, see here:
https://plugins.jetbrains.com/search?products=idea&search=lsp
and then **if they work** fine then we can use our **Language Server** with them.

I tried the [LSP Support Plugin](https://plugins.jetbrains.com/plugin/10209-lsp-support) and it "worked".

See the screenshot below:

![Screenshot_2023-04-03_23-12-37](https://user-images.githubusercontent.com/251478/229638621-80ee4f51-348f-4fee-8f0d-d636c8109a47.png)

But after some seconds the "Problems" panel is cleared... I looked at the IDE logs and found this stack trace:

```
2023-04-03 22:41:42,559 [ 878045] SEVERE - #c.i.i.p.PluginManager - Invalid range specified: (37, 36); 
java.lang.IllegalArgumentException: Invalid range specified: (37, 36); 
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:231)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:226)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:222)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:41)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:30)
	...
	truncated
```

so it looks like the Terramate Language Server is sending an invalid range. This never triggers on VSCode then maybe VSCode just handle bad ranges nicely.
The same issue happens with [GoLand](https://www.jetbrains.com/go/).

I created the issue https://github.com/mineiros-io/terramate-ls/issues/33 and I will investigate the cause when I have time.

# [Jetbrains Fleet](https://www.jetbrains.com/fleet)

The Fleet supports LSP as documented [here](https://www.jetbrains.com/help/fleet/smart-mode.html#smart-mode-under-the-hood) but they don't support custom languages... The languages that they support LSP have their language-servers bundled into *Fleet*. Maybe in the future they add an option for custom languages and then maybe Terramate will be supported right away.

# Syntax Highlight

The [Terramate VSCode Extension](https://github.com/mineiros-io/vscode-terramate) implements Syntax Highlight using the [TextMate Grammar](https://macromates.com/manual/en/language_grammars) and Jetbrains supports the same format.
I tried to just use the same grammar file and it partially applied the highlight, most constructs were not highlighted... It seems the VSCode implementation differs a bit but with some tweaks we can probably make it work with low effort.

If someone wants to check this, what I did was just press `CTRL + ALT + S` then go to `Editor -> TextMate Bundles` and then click in `+` to import a bundle and then select the directory of the cloned [vscode-terramate](https://github.com/mineiros-io/vscode-terramate) repo.
This [answer](https://youtrack.jetbrains.com/issue/IDEA-300626/Support-loading-textmate-bundle-in-json-format?IssueComments) in the Jetbrains issue tracker says that this should work.

This was just an initial investigation for supporting Jetbrains IDEs and I will update this issue when I have more information about the problems I mentioned.
Thanks for bringing this to our attention.

**Comment by timsolovev** [comment]
@soerenmartius @i4ki I've been working on implementing the Jetbrains plugin based on the official [LSP API](https://plugins.jetbrains.com/docs/intellij/language-server-protocol.html). It is still pretty buggy, and I'm yet to finish some quality-of-life features, such as bracket collapsing, as well as syntax highlighting for embedded HCL (not speaking of Terraform autocompletion, as requested in #1650). Let me know what you think!

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/3cf2ad85-1e21-4b05-9cc1-21f3e2bea4a9" />

<img width="1398" alt="Image" src="https://github.com/user-attachments/assets/78f1b0bd-3613-41eb-9e01-2fd06b805cff" />

**Comment by ImIOImI** [comment]
I'm very interested in this, and the DX of using terramate really suffers without some of the above listed issues. Jump to definition is especially important to me.
